const preguntas = [
   new Pregunta(
      1, 
      "radio", 
      "¿Cual es el objetivo del Diseño conceptual de Base de Datos?", 
      "-", 
      "Representar la información obtenida del usuario mediante estándares", 1, 
      "Generar un esquema con las estructuras del modelo de Bases de Datos que se va a utilizar.", 0, 
      "Escribir las estructuras del modelo de Bases de Datos en Lenguaje SQL", 0, 
      "Organizar los requisitos del usuario en lenguaje natural", 0, 
      "a", 
      "", 
      ),
      
      new Pregunta(
      2, 
      "radio", 
      "¿Cómo se llama el esquema utilizado en la Fase Conceptual?", 
      "-", 
      "Modelo Relacional", 0, 
      "Flujograma", 0, 
      "Diagrama Entidad-Relación", 1, 
      "Diagrama de Flujo", 0, 
      "c", 
      "", 
      ),
      
      new Pregunta(
      3, 
      "radio", 
      "¿Cuáles son los elementos del Diagrama Entidad-Relación?", 
      "-", 
      "Tablas, Registros, Campos, Valores, Claves, Relaciones", 0, 
      "Entidades, Atributos, Relaciones, Identificadores", 1, 
      "Procesos, Subprocesos, Conectores, Decisores", 0, 
      "Elementos, Frontera, Relaciones, Objetivo", 0, 
      "b", 
      "", 
      ),
      
      new Pregunta(
      4, 
      "radio", 
      "¿A qué se denomina ENTIDAD?", 
      "-", 
      "A cualquier objeto o elemento con características comunes acerca del cual se desee almacenar información en la BD.", 1, 
      "A la unidad básica de las Base de Datos Relacionales,utilizada para organizar la información", 0, 
      "Al diagrama que se utiliza para expresar el Diseño Conceptual en estándares", 0, 
      "A los elementos básicos de la Base de Datos", 0, 
      "a", 
      "", 
      ),
      
      new Pregunta(
      5, 
      "radio", 
      "¿Qué es un atributo?", 
      "-", 
      "Son los componentes, que característican a un elemento, indicando cómo se muestra el contenido que se está definiendo.", 0, 
      "A la parte del diagrama Entidad-Relación que representa las características de una entidad (aquello que se desea guardar sobre la misma).", 1, 
      "A la asociación que existe entre dos o más entidades.", 0, 
      "Al número de ocurrencias de una entidad asociadas a una ocurrencia de la otra entidad.", 0, 
      "b", 
      "", 
      ),
      
      new Pregunta(
      6, 
      "radio", 
      "¿A qué se llama Identificador?", 
      "-", 
      "A todo aquello que se desea guardar sobre las entidades", 0, 
      "A los componentes que conforman un sistema.", 0, 
      "A aquel atributo (o conjunto de atributos) que identifiquen de manera inequívoca a una instancia de la entidad,", 1, 
      "Al output (función) o razón de ser de un sistema.", 0, 
      "c", 
      "", 
      ),
      
      new Pregunta(
      7, 
      "radio", 
      "¿Qué se define como Relación en el Diseño conceptual de Base de Datos?", 
      "-", 
      "A la asociación que existe entre dos a más entidades.", 1, 
      "Las relaciones son la forma en la cual los elementos de un sistema interactúan entre sí.", 0, 
      "A la asociación que existe entre dos a más tablas.", 0, 
      "A aquello que representa cualquier tipo de operación", 0, 
      "a", 
      "", 
      ),
      
      new Pregunta(
      8, 
      "radio", 
      "¿Cómo se denominan las características o propiedades de las relaciones?", 
      "-", 
      "Cardinalidad", 0, 
      "Variedad", 0, 
      "Atributos de la Relación", 1, 
      "Conectores", 0, 
      "c", 
      "", 
      ),
      
      new Pregunta(
      9, 
      "radio", 
      "¿A qué se denomina cardinalidad de una relación?", 
      "-", 
      "Al campo que permite identificar de forma inequívoca el objeto de una tabla.", 0, 
      "A las interrelaciones más o menos estables entre los componentes de un sistema", 0, 
      "Al número de ocurrencias de una entidad asociadas a una ocurrencia de la otra entidad.", 1, 
      "A aquello que permite prever las modificaciones que va a sufrir un sistema y las compensa", 0, 
      "c", 
      "", 
      ),
      
      new Pregunta(
      10, 
      "radio", 
      "¿Cómo se define la cardinalidad entre entidades?", 
      "-", 
      "Considerando cuantos elementos de una entidad pueden pertenecer a otra (en ambas direcciones) y seleccionando los valores de la entidad a la derecha de la relación.", 0, 
      "Considerando cuantos elementos de una entidad pueden pertenecer a otra (en ambas direcciones) y seleccionando los valores de la entidad a la izquierda de la relación.", 0, 
      "Considerando cuantos elementos de una entidad pueden pertenecer a otra (en ambas direcciones) y seleccionando el mínimo de cada una de las partes.", 0, 
      "Considerando cuantos elementos de una entidad pueden pertenecer a otra (en ambas direcciones) y seleccionando el máximo de cada una de las partes.", 1, 
      "d", 
      "", 
      ),
      new Pregunta(
         11, 
         "radio", 
         "¿Qué permite la fase de Diseño lógico de Bases de Datos?", 
         "-", 
         "Realizar una abstracción del sistema que se está estudiando.", 0, 
         "Describir la estructura lógica global de la Base de Datos:las tablas, sus campos y relaciones.", 1, 
         "Simplificar y resaltar de manera deliberada las características más relevantes de la misma.", 0, 
         "Crear las estructuras en el lenguaje específico de la Base de Datos que se va a utilizar.", 0, 
         "b", 
         "", 
         ),
         
         new Pregunta(
         12, 
         "radio", 
         "Señala las características que debe tener la clave primaria", 
         "-", 
         "Su valor no puede repetirse a lo largo de la tabla aunque podría quedar vacía.", 0, 
         "Su valor no puede repetirse a lo largo de la tabla y nunca puede quedar vacía.", 1, 
         "Muestra alguna característica del objeto de la tabla.", 0, 
         "Equivale a la información contenida en cada campo de un registro", 0, 
         "b", 
         "", 
         ),
         
         new Pregunta(
         13, 
         "radio", 
         "¿Cómo se realiza la transformación de las relaciones 1:1 del Diseño Conceptual al Diseño Lógico?", 
         "-", 
         "Se transforma la relación en una nueva tabla que tendrá como clave primaria la concatenación de las claves primarias de las entidades asociadas", 0, 
         "Se propaga la clave primaria de la entidad con cardinalidad máxima 1 a la entidad con cardinalidad máxima n.", 0, 
         "En el 90% se los casos, se fusionan ambas entidades, formando una única tabla.", 1, 
         "Se representa la interacción en forma de red", 0, 
         "c", 
         "", 
         ),
         
         new Pregunta(
         14, 
         "radio", 
         "¿Cómo se realiza la transformación de las relaciones 1:n del Diseño Conceptual al Diseño Lógico?", 
         "-", 
         "Se transforma la relación en una nueva tabla que tendrá como clave primaria la concatenación de las claves primarias de las entidades asociadas", 0, 
         "Se propaga la clave primaria de la entidad con cardinalidad máxima 1 a la entidad con cardinalidad máxima n.", 1, 
         "En el 90% se los casos, se fusionan ambas entidades,formando una única tabla.", 0, 
         "Se representa la interacción en forma de red", 0, 
         "b", 
         "", 
         ),
         
         new Pregunta(
         15, 
         "radio", 
         "¿Cómo se realiza la transformación de las relaciones n:m del Diseño Conceptual al Diseño Lógico?", 
         "-", 
         "Se transforma la relación en una nueva tabla que tendrá como clave primaria la concatenación de las claves primarias de las entidades asociadas", 1, 
         "Se propaga la clave primaria de la entidad con cardinalidad máxima 1 a la entidad con cardinalidad máxima n.", 0, 
         "En el 90% se los casos, se fusionan ambas entidades, formando una única tabla.", 0, 
         "Se representa la interacción en forma de red", 0, 
         "a", 
         "", 
         ),
         
         new Pregunta(
         16, 
         "radio", 
         "¿Qué significa que las columnas de las tablas sólo deban tener valores atómicos?", 
         "-", 
         'Atómica significa "indivisible", es decir, cada campo debe contener un único valor.', 1, 
         "Que cada atributo debe tener un nombre único.", 0, 
         "Que cada campo sólo pueda guardar información de un tipo", 0, 
         "Que los valores a guardar en un campo estén restringidos", 0, 
         "a", 
         "", 
         ),
         
         new Pregunta(
         17, 
         "radio", 
         "¿A qué se refiere la expresión en una tabla no deben existir campos multivaluados?", 
         "-", 
         "Que cada campo sólo pueda guardar información de un tipo", 0, 
         "Que cada campo solo debe guardar un sólo valor", 1, 
         "Que los valores a guardar en un campo estén restringidos", 0, 
         "Que los valores de las columnas sean indivisibles.", 0, 
         "b", 
         "", 
         ),
         
         new Pregunta(
         18, 
         "radio", 
         "¿A qué se refiere la regla eliminar los campos que no dependan de la clave?", 
         "-", 
         "Que los valores a guardar en un campo estén restringidos", 0, 
         "A eliminar los datos redundantes.", 0, 
         "A que todos los campos de la tabla deben poder identificarse al 100% por el campo clave.", 1, 
         "A eliminar los campos que contienen más de un valor", 0, 
         "c", 
         "", 
         ),
         
         new Pregunta(
         19, 
         "checkbox", 
         "¿Por qué en una tabla NUNCA se deben guardan campos que se puedan calcular? (Selecciona las que apliquen)", 
         "-", 
         "Para evitar costes de tiempo en la actualización de los mismos", 0.5, 
         "Por que se requiere mucho más espacio guardando el resultado", 0, 
         "Por que los cálculos los hace el SGBD a partir de la Base de Cálculo, evitando errores humanos", 0.5, 
         "Porque da pie a tener campos multivaluados", 0, 
         "a, c", 
         "", 
         ),
         
         new Pregunta(
         20, 
         "radio", 
         "¿Cual es el objetivo del Diseño Físico de Base de Datos?", 
         "-", 
         "Representar la información obtenida del usuario mediante estándares", 0, 
         "Crear finalmente la estructura de Datos en el lenguaje específico de la Base de Datos que se va a utilizar.", 1, 
         "Organizar los requisitos del usuario en lenguaje natural", 0, 
         "Simplificar y resaltar de manera deliberada las características físicas del modelo", 0, 
         "b", 
         "", 
         ),     
      
       
]

const NUM_PREGUNTAS = preguntas.length;