const preguntas = [
   new Pregunta(
      1, 
      "checkbox", 
      "Señala todas las características que apliquen a una campaña de e-mail marketing", 
      "-", 
      "Se envía a usuarios suscritos a una lista o base de datos determinada, con los que no necesariamente has tenido una relación comercial previa.", 0.5, 
      "Se envía a varios destinatarios simultáneamente", 0.5, 
      "Se utiliza para la confirmación de registro", 0, 
      "Responden a un evento", 0, 
      "a,b", 
      "", 
      ),
      
      new Pregunta(
      2, 
      "radio", 
      "¿Qué es un Newsletter?", 
      "-", 
      "Es una publicación digital de publicidad utilizada para promocionar servicios y productos de una marca.", 0, 
      "Es una publicación digital más bien informativa que se distribuye a través del correo electrónico con cierta periodicidad", 1, 
      "Es una técnica utilizada por las marcas para contactar con su público objetivo a través del correo electrónico.", 0, 
      "Es una publicación digital informativa que se distribuye a través de RSS", 0, 
      "b", 
      "", 
      ),
      
      new Pregunta(
      3, 
      "radio", 
      "¿Qué es una lista de suscriptores? Selecciona la opción más acorde.", 
      "-", 
      "Es una lista de contactos diseñada para enviarles campañas de e-mail marketing", 1, 
      "Es la Base de Datos de clientes potenciales y no potenciales de la empresa.", 0, 
      "Es un grupo de direcciones de e-mail segmentadas de acuerdo a ciertas categorías.", 0, 
      "Es la lista de todos los seguidores de las Redes Sociales de la empresa.", 0, 
      "a", 
      "", 
      ),
      
      new Pregunta(
      4, 
      "checkbox", 
      "¿De qué forma se pueden agregar suscriptores? Selecciona las que apliquen", 
      "-", 
      "De forma manual", 0.33, 
      "Excel, CSV", 0.33, 
      "Desde Bases de datos", 0, 
      "Importandolos desde servicios como Google contacts.", 0.33, 
      "a,b,d", 
      "", 
      ),
      
      new Pregunta(
      5, 
      "checkbox", 
      "¿Cual es la diferencia entre enviar un mail desde un cliente de correo electrónico y hacerlo desde un programa de e-mail marketing? Selecciona las que apliquen:", 
      "-", 
      "La base de datos debe de estar registrada en la Agencia Española de Protección de Datos.", 0.33, 
      "El mensaje deberá llevar un enlace para que el usuario pueda tener acceso a editar, modificar o borrar su correo electrónico de la lista de suscriptores.", 0.33, 
      "Es necesario en adelante un consentimiento explícito del suscriptor.", 0.33, 
      "No es necesario registrar la lista de suscriptores en la Agencia Española de Protección de Datos.", 0, 
      "a,b,c", 
      "", 
      ),
      
      new Pregunta(
      6, 
      "radio", 
      "¿Qué es un suscriptor en email marketing?", 
      "-", 
      "Es toda aquella persona que se encuentre registrada en la lista de suscriptores en un programa de e-mail marketing.", 0, 
      "Es toda aquella persona que se encuentre registrada en la Base de Datos de la empresa como cliente o contacto.", 0, 
      "Es toda aquella persona que haya facilitado sus datos y haya dado su consentimiento de forma explícita para recibir información.", 1, 
      "Es toda aquella persona que se encuentre registrada en una lista de contactos de correo electrónico.", 0, 
      "c", 
      "", 
      ),
      
      new Pregunta(
      7, 
      "radio", 
      "Un formulario de suscripción es...", 
      "-", 
      "Una página web que permite a un usuario suscribirse a una lista, para recibir en su correo electrónico lo que sea que quieras enviarle.", 1, 
      "Un mensaje de correo al cual un usuario da respuesta con sus datos y accede explicitamente a recibir información periódica en su correo electrónico.", 0, 
      "Una página web que capta los datos de los clientes mediante cookies y las suscribe automáticamente a una lista, para posteriormente enviarle campañas promocionales.", 0, 
      "La definición de formulario de suscripción no se encuentra entre el resto de las opciones", 0, 
      "a", 
      "", 
      ),
      
      new Pregunta(
      8, 
      "radio", 
      "¿Qué es un autoresponder?", 
      "-", 
      "Un mensaje de correo que se envía automáticamente al hacer clic en un botón de una página web, solicitando información.", 0, 
      "Una plantilla de correo guardada en la aplicación de email marketing para ser utilizada en ciertos casos.", 0, 
      "Se trata de una secuencia de mensajes de correos predefinida, con respuestas automáticas a diferentes eventos, como puede ser, la suscripción a una lista de correo.", 1, 
      "Un mensaje de correo que le envía automáticamente a la lista de suscripción cada nuevo post del blog de la empresa.", 0, 
      "c", 
      "", 
      ),
      
      new Pregunta(
      9, 
      "radio", 
      "¿Qué es y cómo funciona la segmentación de la audiencia?", 
      "-", 
      "Es la división por categorías de la audiencia en términos de la cantidad de mails abiertos, clicados o rebotados.", 0, 
      "Es la división por categorías de la audiencia con el fin de poder enviarles campañas de email marketing específicas.", 1, 
      "Son palabras clave que te ayudan a organizar mejor los contactos.", 0, 
      "La segmentación es un tema de Tablas Dinámicas de Excel", 0, 
      "b", 
      "", 
      ),
      
      new Pregunta(
      10, 
      "radio", 
      "¿Cómo clasifica las campañas el Mailchimp?", 
      "-", 
      "EMail, Ad, Landing page, Postcard, Social Post, Signup Form", 1, 
      "EMail, Ad, Landing page, Signup Form, Mercadotecnia por permiso", 0, 
      "EMail, Campañas A/B, Postcards, Social Post, Signup Form", 0, 
      "EMail, Autoresponders, Postcards, Posts, Signup Form", 0, 
      "a", 
      "", 
      ),
      new Pregunta(
         11, 
         "radio", 
         "¿A qué se refiere la opción Field Tag del Formulario de Suscripción?", 
         "/img/emailmkt/P11.png", 
         "A una etiqueta que se le aplica al campo", 0, 
         "Al nombre que tiene un campo en la lista de suscriptores", 1, 
         "Al nombre del campo en el idioma original del Mailchimp que es inglés.", 0, 
         "La respuesta no coincide con el resto de las opciones", 0, 
         "b", 
         "", 
         ),
         
         new Pregunta(
         12, 
         "radio", 
         "¿Qué se denomina E-mail marketing transaccional?", 
         "-", 
         "A un envío realizado desde una lista de suscriptores", 0, 
         "A un envío que deriva de una transacción realizada por un usuario y que da como resultado que quede registrado como lead o subscrito a un Newsletter.", 1, 
         "A un alta durante un procesos de compra", 0, 
         "A una llamadas a la acción en correos transaccionales", 0, 
         "b", 
         "", 
         ),
         
         new Pregunta(
         13, 
         "radio", 
         "¿A qué se refiere la propuesta de valor para los suscriptores?", 
         "-", 
         "A brindar una solución sobre cómo tu empresa, producto o servicio resuelve de forma diferenciada el problema o necesidad de tu cliente.", 1, 
         "A la descripción del producto y/o servicio que se presta.", 0, 
         "La misión, visión y objetivos de la empresa", 0, 
         "Es un párrafo que le indica al cliente por qué debería comprarte.", 0, 
         "a", 
         "", 
         ),
         
         new Pregunta(
         14, 
         "radio", 
         "¿A qué se refiere el término BROADCAST?", 
         "-", 
         "Cada vez que se publique un nuevo artículo a un Blog o Sitio de Noticias, este contenido es automáticamente cargado en una pieza de Email y enviado a las Listas de Suscriptores.", 0, 
         "Es una campaña destinada a destacar productosdeterminados o dar a conocer novedades.", 0, 
         "Es un envío masivo que se caracteriza por enviar un mismo mensaje a una lista completa o a un segmento de una lista, en un único momento.", 1, 
         "Es una campaña destinada a realizar ofertas y promociones.", 0, 
         "c", 
         "", 
         ),
         
         new Pregunta(
         15, 
         "radio", 
         "¿Qué es un Test A/B? (Selecciona la más apropiada)", 
         "-", 
         "Son campañas que se lanzan para evaluar la actuación de las diferentes variables que la componen.", 1, 
         "Son campañas que se lanzan para evaluar la aceptación del estilo de un newsletter.", 0, 
         "Son campañas que se lanzan para evaluar el momento de envío más adecuado para un newsletter.", 0, 
         "Son campañas que se lanzan para evaluar el asunto que logra más tasas de apertura al enviar un newsletter.", 0, 
         "a", 
         "", 
         ),
         
         new Pregunta(
         16, 
         "radio", 
         "¿Qué es la tasa de apertura en E-Mail Marketing?", 
         "-", 
         "La proporción de correos electrónicos abiertos por tus contactos en comparación con la cantidad de correos electrónicos entregados.", 1, 
         "Es el número de suscriptores que hacen clic en uno o más enlaces de contenidos en tu email, expresados como un porcentaje del total de emails abiertos.", 0, 
         "La proporción de correos electrónicos que regresan al remitente con un mensaje de error porque no se pudo entregar, en comparación con el número total de correos electrónicos enviados.", 0, 
         "El porcentaje de quejas (declaración como correo no deseado) que generó tu campaña.", 0, 
         "a", 
         "Los porcentajes medios de tasa de apertura de correo electrónico suelen ser reducidos (aproximadamente del 20%). https://es.sendinblue.com/blog/estadisticas-email-marketing-indicadores-clave/", 
         ),
         
         new Pregunta(
         17, 
         "radio", 
         "¿Qué es la tasa de clics en E-Mail Marketing?", 
         "-", 
         "La proporción de correos electrónicos abiertos por tus contactos en comparación con la cantidad de correos electrónicos entregados.", 0, 
         "Es el número de suscriptores que hacen clic en uno o más enlaces de contenidos en tu email, expresados como un porcentaje del total de emails abiertos.", 1, 
         "La proporción de correos electrónicos que regresan al remitente con un mensaje de error porque no se pudo entregar, en comparación con el número total de correos electrónicos enviados.", 0, 
         "El porcentaje de quejas (declaración como correo no deseado) que generó tu campaña.", 0, 
         "b", 
         "Los porcentajes medios de tasa de clics son de acuerdo con estadísticas de 2017, del 3,42 %.", 
         ),
         
         new Pregunta(
         18, 
         "radio", 
         "¿Qué es la tasa de rebote en E-Mail Marketing?", 
         "-", 
         "La proporción de correos electrónicos abiertos por tus contactos en comparación con la cantidad de correos electrónicos entregados.", 0, 
         "Es el número de suscriptores que hacen clic en uno o más enlaces de contenidos en tu email, expresados como un porcentaje del total de emails abiertos.", 0, 
         "La proporción de correos electrónicos que regresan al remitente con un mensaje de error porque no se pudo entregar, en comparación con el número total de correos electrónicos enviados.", 1, 
         "El porcentaje de quejas (declaración como correo no deseado) que generó tu campaña.", 0, 
         "c", 
         "Una tasa superior al 0.1% puede condenarte a ser clasificado como spam", 
         ),
         
         new Pregunta(
         19, 
         "radio", 
         "¿Qué es la tasa de bajas en E-Mail Marketing?", 
         "-", 
         "La proporción de personas que se han dado de baja al recibir una campaña en comparación con la cantidad de correos electrónicos entregados.", 1, 
         "Es el número de suscriptores que hacen clic en uno o más enlaces de contenidos en tu email, expresados como un porcentaje del total de emails abiertos.", 0, 
         "La proporción de correos electrónicos que regresan al remitente con un mensaje de error porque no se pudo entregar, en comparación con el número total de correos electrónicos enviados.", 0, 
         "El porcentaje de quejas (declaración como correo no deseado) que generó tu campaña.", 0, 
         "a", 
         "", 
         ),
         
         new Pregunta(
         20, 
         "radio", 
         "¿A qué se refiere la expresión Hard Bounce en E-Mail Marketing?", 
         "-", 
         "Es un tipo de error que se produce cuando la bandeja de email del destinatario presenta un problema temporal: está llena o el servidor no funciona.", 0, 
         "Es un tipo de error que se produce cuando el email del destinatario no es correcto, está mal escrito o ya no existe.", 1, 
         "Se refiere a la proporción de personas que se han dado de baja al recibir una campaña en comparación con la cantidad de correos electrónicos entregados.", 0, 
         "Se refiere al porcentaje de quejas (declaración como correo no deseado) que generó tu campaña.", 0, 
         "b", 
         "", 
         ),
          
]

const NUM_PREGUNTAS = preguntas.length;