// constructor(id, tipo, pregunta, imagen, 
//    opcionA, valorA, opcionB, valorB, opcionC, valorC, opcionD, valorD, correcta, hint)
const preguntas = [
   new Pregunta(
      1, 
      "radio", 
      "La fórmula =SUMA(A1; B5:B8)", 
      "-", 
      "Suma el valor de A1 con los del rango B5:B8", 1, 
      "Suma A1+B5+B8", 0, 
      "Suma A1 al resultado de la división de B5 entre B8", 0, 
      "La sintaxis de la fórmula mostrada es incorrecta", 0, 
      "a", 
      "La función SUMA permite sumar valores individuales, referencias y/o rangos de celdas o una combinación de las tres.<br>Para ello permite incluir hasta 255 argumentos. El punto y coma, permite separar los argumentos de la función. Los dos puntos, señalan un rango", 
      ),
   new Pregunta(
      2, 
      "radio", 
      "La función que permite ocultar errores provenientes de una fórmula es...", 
      "-", 
      "SIND", 0, 
      "ESBLANCO", 0, 
      "SI.ERROR", 1, 
      "SI", 0, 
      "c", 
      "", 
   ),
   new Pregunta(
      3, 
      "radio", 
      "Para sumar valores de un rango de dato, que cumplan cierta condición usamos la función...", 
      "-", 
      "SUMA", 0, 
      "SUMAR.SI", 1, 
      "SUMAPRODUCTO", 0, 
      "SI(condición; SUMA( ... ); 0)", 0, 
      "b", 
      "", 
      ),
      
      new Pregunta(
      4, 
      "radio", 
      "¿Qué permite hacer la función CONTAR?", 
      "-", 
      "Contar cuántos números hay en un rango", 1, 
      "Contar cuántas celdas llenas hay en un rango", 0, 
      "Contar cuántas celdas llenas hay en una lista", 0, 
      "Contar las celdas no vacías de un rango.", 0, 
      "a", 
      "", 
      ),
      
      new Pregunta(
      5, 
      "radio", 
      "Para obtener el promedio entre 2, 3 y 5 escribimos...", 
      "-", 
      "=PROMEDIO(2: 3: 5)", 0, 
      "=PROMEDIO(2; 3; 5)", 1, 
      "=PROMEDIO(2+3+5)", 0, 
      "=PROMEDIO(2+3+5)/3", 0, 
      "b", 
      "", 
      ),
      
      new Pregunta(
      6, 
      "radio", 
      "¿Qué nos indica el error #### en Excel?", 
      "-", 
      "Que la fórmula está mal escrita", 0, 
      "Que el resultado de una fórmula no cabe en el ancho de la columna", 1, 
      "Que un valor buscado no se encuentra", 0, 
      "Que se están usando textos en lugar de números", 0, 
      "b", 
      "", 
      ),
      
      new Pregunta(
      7, 
      "radio", 
      "¿Qué resultado me muestra la siguiente fórmula? =SI(B2>=5;APROBADO;SUSPENSO)", 
      "-", 
      "Que aparezca el texto APROBADO, si en B2 hay un valor numérico >=5 ó SUSPENSO si hay un valor <5.", 0, 
      "Aparecerá un mensaje de error", 1, 
      "Que aparezca el texto APROBADO ó SUSPENSO según si contenido es mayor ó menor que 5.", 0, 
      "La función SI mostrada tiene número incorrecto de argumentos", 0, 
      "b", 
      "", 
      ),
      
      new Pregunta(
      8, 
      "radio", 
      "Indica cual de estas funciones está escrita de manera CORRECTA:", 
      "-", 
      "=FECHA()", 0, 
      "=HOY(21/06/2019)", 0, 
      "=HOY()", 1, 
      "=FECHA(21/06/2019)", 0, 
      "c", 
      "=HOY(). Esta función muestra en la celda la fecha del ordenador.", 
      ),
      
      new Pregunta(
      9, 
      "radio", 
      'Dada la siguiente imagen: ¿Qué resultado daría la fórmula? =CONTAR.SI(B1:B9;"GIRONA")', 
      "Verdadero", 
      "1", 0, 
      "3", 1, 
      "€400", 0, 
      "La sintaxis de la función es errónea", 0, 
      "b", 
      "", 
      ),
      
      new Pregunta(
      10, 
      "radio", 
      "¿Cual de estas funciones cuenta la cantidad de celdas que NO están vacías?", 
      "-", 
      "CONTAR", 0, 
      "SUMA", 0, 
      "CONTARA", 1, 
      "CONTAR.SI", 0, 
      "c", 
      "", 
      ),
      new Pregunta(
         11, 
         "radio", 
         "¿ Qué hace el operador & de Excel ?", 
         "-", 
         "Repite", 0, 
         "Une", 1, 
         "Compara", 0, 
         "Sustituye", 0, 
         "b", 
         "", 
         ),
         
         new Pregunta(
         12, 
         "radio", 
         "Dada la siguiente imagen... ¿Qué resultado daría la siguiente fórmula? =BUSCARV(G1; F5:G9; 2; FALSO)", 
         "-", 
         "La fórmula contiene un número errado de argumentos", 0, 
         "3,0%", 0, 
         "#N/A", 1, 
         "3,5%", 0, 
         "c", 
         "", 
         ),
         
         new Pregunta(
         13, 
         "radio", 
         "Dada la siguiente imagen... ¿Qué resultado daría la siguiente fórmula? =BUSCARV(G1; F5:G9; 2; VERDADERO)", 
         "Verdadero", 
         "La fórmula contiene un número errado de argumentos", 0, 
         "3,0%", 1, 
         "#N/A", 0, 
         "3,5%", 0, 
         "b", 
         "", 
         ),
         
         new Pregunta(
         14, 
         "checkbox", 
         "La herramienta Validación de Datos... (indica todas las opciones correctas)", 
         "-", 
         "permite restringir los valores que los usuarios escriben en una celda.", 0.33, 
         "permite mostrar en un mensaje la forma de llenar una celda", 0.33, 
         "permite desplegar una lista de opciones en una celda", 0.33, 
         "pinta la celda de un color si su valor es inválido", 0, 
         "a,b,c", 
         "", 
         ),
         
         new Pregunta(
         15, 
         "radio", 
         "Si quisiera ubicar la posición del valor en L2 en el rango I2:I8 utilizo la función", 
         "Verdadero", 
         "INDICE", 0, 
         "BUSCARV", 0, 
         "COINCIDIR", 1, 
         "K.ESIMO", 0, 
         "c", 
         "", 
         ),
         
         new Pregunta(
         16, 
         "radio", 
         "Indica la función que devuelva el valor 'jueves'", 
         "Verdadero", 
         "=BUSCARV(L2; $I$2:$I$8; 1; FALSO)", 0, 
         "=DIASEM(L2)", 0, 
         "=INDICE($I$2:$I$8; L2)", 1, 
         "=COINCIDIR(L2; $I$2:$I$8; 0)", 0, 
         "c", 
         "", 
         ),
         
         new Pregunta(
         17, 
         "radio", 
         "¿Con cuál de las siguientes funciones podríamos sumar las ventas comprendidas entre €100 y €250?", 
         "Verdadero", 
         "Con la función SI", 0, 
         "Con SUMAR.SI", 0, 
         "Con BUSCARV", 0, 
         "Con SUMAR.SI.CONJUNTO", 1, 
         "d", 
         "", 
         ),
         
         new Pregunta(
         18, 
         "radio", 
         "¿Qué herramienta de Excel deberíamos utilizaren el rango C2:C9 para que luzca como en la imagen?", 
         "Verdadero", 
         "Insertar - Minigráficos", 0, 
         "Insertar - Símbolos", 0, 
         "Inicio - Formato condicional", 1, 
         "Estilos de celda", 0, 
         "c", 
         "", 
         ),
         
         new Pregunta(
         19, 
         "radio", 
         "¿Qué es un nombre de rango?", 
         "-", 
         "Es la intersección de una fila con una columna", 0, 
         "Es un nombre que se le asigna al libro de Excel, desde el cuadro de nombres, para referenciarlo posteriormente", 1, 
         "Es un argumento en las funciones de Excel", 0, 
         "Es el nombre de la celda superior izquierda seguido de dos puntos y a continuación el nombre de la celda inferior derecha en un conjunto de celdas.", 0, 
         "b", 
         "", 
         ),
         
         new Pregunta(
         20, 
         "radio", 
         "En Excel, la siguiente fórmula: =[@Cantidad]*[@Precio]", 
         "-", 
         "Permite multiplicar el valor de la columna Cantidad * el valor de la columna Precio de una fila determinada en una tabla de Datos de Excel.", 1, 
         "Es una fórmula DAX en Power BI, no es una fórmula de Excel", 0, 
         "Es una fórmula que multiplica los campos Cantidad y Precio en una consulta de Access.", 0, 
         "Tiene una sintaxis errónea", 0, 
         "a", 
         "", 
         ),
]


const NUM_PREGUNTAS = preguntas.length;