const preguntas = [
   new Pregunta(
      1, 
      "radio", 
      "¿Cuál es el código HTML correcto para un salto de línea? ", 
      "-", 
      "&lt;br&gt;", 1, 
      "&lt;break/&gt;", 0, 
      "&lt;/p&gt;", 0, 
      "El resto de las opciones es incorrecta", 0, 
      "a", 
      "", 
      ),
   /*   
      new Pregunta(
      2, 
      "radio", 
      "En HTML, los elementos de una lista se definen con:", 
      "-", 
      "<li>", 1, 
      "<ol>", 0, 
      "<option>", 0, 
      "<ul>", 0, 
      "a", 
      "", 
      ),
      
      new Pregunta(
      3, 
      "radio", 
      "En HTML, las etiquetas <p> </p> se utiliza para", 
      "-", 
      "Definir un punto de destino para un hipervínculo", 0, 
      "Insertar un salto de línea", 0, 
      "Definir un párrafo", 1, 
      "Indicar los elementos de una lista", 0, 
      "c", 
      "", 
      ),
      
      new Pregunta(
      4, 
      "radio", 
      "En HTML, para referenciar una hoja de estilo externa se emplea la etiqueta <link> con el atributo", 
      "-", 
      "href", 1, 
      "src", 0, 
      "url", 0, 
      "La respuesta no se encuentra entre las opciones mostradas", 0, 
      "a", 
      "", 
      ),
      
      new Pregunta(
      5, 
      "radio", 
      "En HTML, la forma correcta de crear un comentario es", 
      "-", 
      "<-- El comentario -->", 0, 
      "<--! El comentario !-->", 0, 
      "<--! El comentario -->", 0, 
      "<!-- El comentario -->", 1, 
      "d", 
      "", 
      ),
      
      new Pregunta(
      6, 
      "radio", 
      "En HTML, cuál de las siguientes afirmaciones es cierta", 
      "-", 
      "La etiqueta <ol> debe ir anidada dentro de la etiqueta <li>", 0, 
      "La etiqueta <p> debe ir anidada dentro de la etiqueta <h1>", 0, 
      "La etiqueta <li> debe ir anidada dentro de la etiqueta <ul>", 1, 
      "La etiqueta <html> debe ir anidada dentro de la etiqueta <body>", 0, 
      "c", 
      "", 
      ),
      
      new Pregunta(
      7, 
      "radio", 
      "Las etiquetas <ol> y <li> se emplean para crear", 
      "-", 
      "Una tabla de datos", 0, 
      "Una lista numerada", 1, 
      "Una lista con viñetas", 0, 
      "La respuesta no se encuentra entre las opciones mostradas", 0, 
      "b", 
      "", 
      ),
      
      new Pregunta(
      8, 
      "radio", 
      "En HTML, la etiqueta <title> se emplea para", 
      "-", 
      "Definir el título de la página web", 1, 
      "Definir el nombre de un elemento", 0, 
      "Proporcionar información adicional sobre un elemento", 0, 
      "Definir el título de una tabla", 0, 
      "a", 
      "", 
      ),
      
      new Pregunta(
      9, 
      "radio", 
      "En HTML, las etiquetas <h1>, <h2> y <h3> se emplean para definir", 
      "-", 
      "Hipervínculos", 0, 
      "Encabezados", 1, 
      "Listas", 0, 
      "Tablas", 0, 
      "b", 
      "", 
      ),
      
      new Pregunta(
      10, 
      "radio", 
      "¿A dónde se dirige el siguiente enlace? &lt;a href='indice.html'&gt;Índice&lt;/a&gt;", 
      "-", 
      "A otra página en el mismo sitio web, llamada indice", 1, 
      "A otra página en otro sitio web", 0, 
      "A una parte en la misma página web", 0, 
      "La respuesta no se encuentra entre las opciones mostradas", 0, 
      "a", 
      "", 
      ),
      new Pregunta(
         11, 
         "radio", 
         "En HTML, para crear un hipervínculo se emplea la etiqueta", 
         "-", 
         "<link>", 0, 
         "<href>", 0, 
         "<a>", 1, 
         "<rel>", 0, 
         "c", 
         "", 
         ),
         
         new Pregunta(
         12, 
         "radio", 
         "¿Cuál es el lugar correcto en un documento HTML para hacer referencia a una hoja de estilos externa?", 
         "-", 
         "Al principio del documento", 0, 
         "En la sección <head>", 1, 
         "En la sección <body>", 0, 
         "Al final del documento", 0, 
         "b", 
         "", 
         ),
         
         new Pregunta(
         13, 
         "radio", 
         "¿Cómo se le llama a un documento HTML que está disponible a través de la World Wide Web y se puede acceder a través de un navegador web?", 
         "-", 
         "PHP", 0, 
         "Página web", 1, 
         "Home page", 0, 
         "Landing Page", 0, 
         "b", 
         "", 
         ),
         
         new Pregunta(
         14, 
         "radio", 
         "¿Qué son los atributos en HTML?", 
         "-", 
         "Son los bloques de construcción del HTML.", 0, 
         "Son los componentes, que característican a un elemento, indicando cómo se muestra el contenido que está definiendo.", 1, 
         "Son los componentes que identifican diferentes partes de una página web utilizando etiquetas", 0, 
         "Son los símbolos que habitualmente no se encuentran en el teclado", 0, 
         "b", 
         "", 
         ),
         
         new Pregunta(
         15, 
         "radio", 
         "¿Qué son los elementos en HTML?", 
         "-", 
         "Son los bloques de construcción del HTML, que identifican diferentes partes de una página web utilizando etiquetas", 1, 
         "Son los componentes, que característican a un elemento, indicando cómo muestra el contenido que está definiendo.", 0, 
         "Son los símbolos que habitualmente no se encuentran en el teclado", 0, 
         "Es aquella parte de la página web donde se colocan los metadatos y se define la configuración.", 0, 
         "a", 
         "", 
         ),
         
         new Pregunta(
         16, 
         "radio", 
         "¿Cuáles son las dos secciones principales de un documento HTML?", 
         "-", 
         "<title> y <content>", 0, 
         "<html> y <css>", 0, 
         "<head> y <body>", 1, 
         "<meta> y <link>", 0, 
         "c", 
         "", 
         ),
         
         new Pregunta(
         17, 
         "radio", 
         "¿Qué es una aplicación multiplataforma?", 
         "-", 
         "Que funciona en diferentes dispositivos", 0, 
         "Que funciona en diferentes sistemas operativos", 1, 
         "Que funciona en diferentes redes: local y compartida", 0, 
         "Una aplicación plenamente funcional.", 0, 
         "b", 
         "", 
         ),
         
         new Pregunta(
         18, 
         "radio", 
         "¿Para que se usa la etiqueta <iframe>?", 
         "-", 
         "Para dibujar un rectángulo en la página", 0, 
         "Para crear una nueva sección", 0, 
         "Para mostrar contenidos de otras páginas, por ejemplo un video.", 1, 
         "Para incluir imágenes en el contenido de una página.", 0, 
         "c", 
         "", 
         ),
         
         new Pregunta(
         19, 
         "radio", 
         "¿Qué es un hosting o alojamiento web?", 
         "-", 
         "Es la empresa que brinda conexión a Internet a sus clientes.", 0, 
         "Es un número que identifica, de manera lógica y jerárquica, a una Interfaz en red", 0, 
         "Son las siglas que se utilizan para denominar a la dirección específica que se le asigna a cada página web", 0, 
         "Es el espacio donde se aloja un sitio web para que cualquiera pueda verlo en Internet", 1, 
         "d", 
         "", 
         ),
         
         new Pregunta(
         20, 
         "radio", 
         "¿Cómo se le debe llamar al a página principal de un sitio web?", 
         "-", 
         "indice", 0, 
         "index", 1, 
         "html", 0, 
         "landingpage", 0, 
         "b", 
         "", 
         ),
*/          
]

const NUM_PREGUNTAS = preguntas.length;