const preguntas = [
   new Pregunta(
      1, 
      "radio", 
      "Una Tabla de Datos es:", 
      "-", 
      "Un rango de celdas que tiene una cabecera con los nombres de campo y una o más filas denominados registros.", 1, 
      "Una hoja de Excel con información relacionada.", 0, 
      "Un rango de celdas contiguas al cual se le ha dado un nombre.", 0, 
      "Una tabla con información estadística producto del cruce de filas y columnas", 0, 
      "a", 
      "", 
      ),
      
      new Pregunta(
      2, 
      "radio", 
      "Para poder crear una tabla dinámica... (selecciona la que más se ajuste a la realidad)", 
      "-", 
      "...es necesario seleccionar previamente los datos de origen.", 0, 
      "...los datos de origen se pueden seleccionar en un paso posterior.", 1, 
      "...no es necesario tener datos de origen", 0, 
      "...Hay que dar nombre a un rango, el cual servirá de origen a la tabla", 0, 
      "b", 
      "", 
      ),
      
      new Pregunta(
      3, 
      "radio", 
      "La función CUENTA sirve para...", 
      "-", 
      "...contar cuantos elementos existen.", 0, 
      "...contar el número de veces que aparece un elemento en la respecto de la fila.", 0, 
      "...contar el número de veces que aparece un elemento en el cruce de filas y columna", 1, 
      "...contar el número de registros que cumplen una condición", 0, 
      "c", 
      "", 
      ),
      
      new Pregunta(
      4, 
      "radio", 
      "Para crear un gráfico dinámico se debe...", 
      "-", 
      "Ir a la pestaña Insertar y seleccionar Gráfico dinámico del listado Tabla dinámica.", 0, 
      "Ir a la pestaña Opciones y hacer clic en el botón Gráfico dinámico.", 0, 
      "Se puede crear tanto desde la pestaña Insertar como desde la pestaña opciones.", 1, 
      "Los Gráficos Dinámicos poseen su propia pestaña", 0, 
      "c", 
      "", 
      ),
      
      new Pregunta(
      5, 
      "radio", 
      "¿Qué representa una FILA en las Tablas Dinámica?", 
      "-", 
      "Los valores que se muestran a la izquierda en la misma", 0, 
      "La agrupación de los valores de un campo, mostrada de forma horizontal.", 1, 
      "Los encabezados de los datos, mostrados en datos en las primeras columnas de la tabla.", 0, 
      "Fila es sinónimo de Registro", 0, 
      "b", 
      "", 
      ),
      
      new Pregunta(
      6, 
      "radio", 
      "¿Se puede arrastrar cualquier campo al cuadro de Valores en una Tabla Dinámica?", 
      "-", 
      "Si, las Tablas Dinámicas permiten aplicar cualquier tipo de función estadística.", 0, 
      "No, sólo se pueden arrastrar valores numéricos", 0, 
      "No, sólo se pueden arrastrar valores numéricos y de fecha", 0, 
      "Si, aunque si el campo guarda textos, las Tablas Dinámicas sólo permiten aplicar la función CUENTA.", 1, 
      "d", 
      "", 
      ),
      
      new Pregunta(
      7, 
      "checkbox", 
      "¿Como se cambia el tipo de estadística que se desea mostrar en una Tabla Dinámica?", 
      "-", 
      "Seleccionandola en la Pestaña Fórmula y luego seleccionando Funciones Estadísticas", 0, 
      "Haciendo clic sobre el botón fx de la Barra de Fórmulas", 0, 
      "Seleccionando en el desplegable del campo en cuestión la opción Configuración de campo de valor", 0.5, 
      "Seleccionar la opción Configuración de Campo en la pestaña Analizar del Menú de Herramientas de Tabla Dinámica.", 0.5, 
      "c, d", 
      "", 
      ),
      
      new Pregunta(
      8, 
      "radio", 
      "¿Cual es la mejor manera de cambiar el formato numérico a un campo de Tabla Dinámica?", 
      "-", 
      "Seleccionando el resultado en la Tabla Dinámica y dandole el Formato desde la Pestaña Inicio de Excel.", 0, 
      "Seleccionando el resultado en la Tabla Dinámica, clicando con el botón derecho sobre el mismo y seleccionando Formato de Número.", 0, 
      "Con la Pestaña Diseño de Herramientas de Tablas Dinámicas", 0, 
      "Con el botón Formato desde el cuadro de diálogo, Configuración de Campo de Valor", 1, 
      "d", 
      "", 
      ),
      
      new Pregunta(
      9, 
      "radio", 
      "Si necesitamos que los campos de una Tabla Dinámica no muestren etiquetas de error tal y como #¡DIV/0!, ¿qué acción tomamos?", 
      "-", 
      "Utilizar la función SI.ERROR para el cálculo del campo", 0, 
      "Configuramos la opción: Para valores erróneos mostrar... en el cuadro de diálogo Opciones de Tabla Dinámica.", 1, 
      "Utilizamos Formato condicional, para ocultar los errores", 0, 
      "Si aparece un mensaje de error, es porque las opciones estadísticas seleccionadas, son incorrectas.", 0, 
      "b", 
      "", 
      ),
      
      new Pregunta(
      10, 
      "checkbox", 
      "¿Es posible agrupar por filas o columnas un campo que guarda numeros o de fecha? ¿Cómo se hace? (      Selecciona todas las opciones posibles).", 
      "-", 
      "Si, es posible. Se arrasta el campo a la sección FILAS o COLUMNAS, se selecciona el primer valor de este campo, y clicando sobre el mismo con el botón derecho, se selecciona la opción Agrupar.", 0.5, 
      "Si, es posible pero tan solo para Filas. Se arrasta el campo a la sección FILAS, se selecciona el primer valor de este campo, y clicando sobre el mismo con el botón derecho, se selecciona la opción Agrupar.", 0, 
      "Es posible arrastrando el campo a la sección FILAS o COLUMNAS, seleccionando el primer valor y luego la opción Agrupar, de la sección Agupar y Esquema en la pestaña Datos.", 0.5, 
      "Sólo es posible agrupar por campos que guardan texto, en las filas o columnas de una Tabla Dinámica", 0, 
      "a y c", 
      "", 
      ),
      new Pregunta(
         11, 
         "radio", 
         "¿Por qué a las Tablas Dinámicas se les da este nombre?", 
         "-", 
         "Porque si los datos de origen cambian, los cálculos de la Tabla Dinámica se actualizan", 0, 
         "Porque se puede cambiar su disposición, reordenando o cambiando de posición los encabezados de fila y columna, rápida y fácilmente.", 1, 
         "Porque se pueden sustituir los datos de origen rápidamente.", 0, 
         "Por la diversidad de cálculos estadísticos que permite.", 0, 
         "b", 
         "", 
         ),
         
         new Pregunta(
         12, 
         "checkbox", 
         "¿Cómo podemos filtrar la informacion que esta dentro de la Tabla Dinámica? (selecciona las que apliquen)", 
         "-", 
         "Utilizando los filtros de los encabezados de Fila/Columna de la Tabla Dinámica", 0.33, 
         "Arrastrando los campos por los que se quiere filtrar a la sección FILTROS", 0.33, 
         "Utilizando la opción Filtros de la pestaña Datos de Excel", 0, 
         "Utilizando la Segmentación de Datos de Tabla Dinámica.", 0.33, 
         "a,b,d", 
         "", 
         ),
         
         new Pregunta(
         13, 
         "radio", 
         "¿Cómo se puede modificar el tipo de cálculo estadístico sobre un campo de valor en una Tabla Dinámica?", 
         "-", 
         "Usando la opción Elementos calculados de la pestaña  Análizar", 0, 
         "Usando la opción Campos calculados de la pestaña Análizar", 0, 
         "Seleccionando la estadística apropiada desde el cuadro de diálogo Configuración de campo de valor", 1, 
         "Haciendo el cálculo en los Datos de Origen y luego reactualizando la Tabla Dinámica", 0, 
         "c", 
         "", 
         ),
         
         new Pregunta(
         14, 
         "checkbox", 
         "¿Es posible calcular diferentes estadísticas para un mismo campo en una Tabla Dinámica?", 
         "-", 
         "Sí es posible, se arrastra el campo más de una vez y se selecciona la estadística deseada desde el cuadro de diálogo Configuración de campo de valor.", 0.5, 
         "Es posible arrastrar un mismo campo a diferentes secciones, pero sólo puede arrastrarse a la sección valores una sola vez.", 0, 
         "Sí es posible, se arrastra el campo más de una vez y se selecciona la opción Resumir Valores por... del menú contextual.", 0.5, 
         "No, no es posible. Un mismo campo sólo puede utilizarse en una Tabla Dinámica una sola vez.", 0, 
         "a, c", 
         "", 
         ),
         
         new Pregunta(
         15, 
         "checkbox", 
         "¿Es posible mostrar un mismo campo en más de una forma en la Tabla Dinámica?", 
         "-", 
         "Sí es posible, se arrastra el campo más de una vez y se selecciona la forma de mostralo desde la opción Mostrar Valores como, en el cuadro de diálogo Configuración de campo de valor.", 0.5, 
         "Es posible arrastrar un mismo campo a diferentes secciones, pero sólo puede arrastrarse a la sección valores una sola vez.", 0, 
         "Sí es posible, se arrastra el campo más de una vez y se selecciona la opción Mostrar Valores como... del menú contextual.", 0.5, 
         "No, no es posible. Un mismo campo sólo puede utilizarse en una Tabla Dinámica una sola vez.", 0, 
         "a, c", 
         "", 
         ),
         
         new Pregunta(
         16, 
         "radio", 
         "Para que sirve la opción % del total de columnas, en  la opción Mostrar Valores como, del cuadro de diálogo Configuración de campo de valor.", 
         "-", 
         "Para mostrar los valores como un porcentaje del total general de todos los valores", 0, 
         "Para mostrar los valores de cada fila como un porcentaje del total de las columnas.", 0, 
         "Para mostrar los valores de cada columna como un porcentaje del total de las columnas.", 1, 
         "Calcula los valores de la siguiente forma: (valor del elemento) / (valor del elemento principal en las columnas)", 0, 
         "c", 
         "", 
         ),
         
         new Pregunta(
         17, 
         "radio", 
         "¿Es posible mostrar u ocultar totales y subtotales en Tablas Dinámicas y cambiar su posición?", 
         "-", 
         "Sí. Es posible mostrar u ocultar totales y subtotales en Tablas Dinámicas así como cambiar su posición, seleccionando si se desea ver en la parte inferior o superior de cada grupo.", 0, 
         "Sí. Es posible mostrar u ocultar totales y subtotales en Tablas Dinámicas pero sólo se permite cambiar la posición, de los subtotales.", 1, 
         "Sí. Es posible mostrar u ocultar subtotales así como y cambiar su posición, no así respecto de los Totales Generales.", 0, 
         "No, no es posible.", 0, 
         "b", 
         "", 
         ),
         
         new Pregunta(
         18, 
         "radio", 
         "¿Con cuántos formatos de Diseño de Informe de Tabla Dinámica permite trabajar Excel?", 
         "-", 
         "Con todos los que se desee, al arrastrar los campos a las secciones, el formato cambia automáticamente.", 0, 
         "Permite dos tipos de formato: tabular y en esquema.", 0, 
         "Permite tres tipos de formato: tabular, compacto y en esquema.", 1, 
         "Permite tres tipos de formato: tabular, en lista y compacto.", 0, 
         "c", 
         "", 
         ),
         
         new Pregunta(
         19, 
         "checkbox", 
         "¿Es posible cambiar los títulos a los campos de las Tablas Dinámicas?", 
         "-", 
         "Si es posible, con la opción Nombre personalizado del cuadro de diálogo, Configuración de Campo de Valor.", 0.33, 
         "Es posible, se reescribe el título en el encabezado de la columna y ya.", 0.33, 
         "Si es posible, en la sección campo activo de la pertaña Analizar del Menú de Herramientas de Tabla Dinámica.", 0.33, 
         "No, es posible. Excel le agrega como prefijo al nombre del campo, el nombre de la Función Estadística utilizada para el cálculo", 0, 
         "a,b,c", 
         "", 
         ),
         
         new Pregunta(
         20, 
         "radio", 
         "¿Qué sucede al hacer doble clic sobre un valor de la Tabla Dinámica?", 
         "-", 
         "Muestra el cuadro de diálogo configuración de campo de valor.", 0, 
         "Permite insertar una Segmentación de Datos", 0, 
         "Genera una nueva hoja donde lista, en forma de tabla, los registros del origen de datos que componen el valor sobre el cual se ha hecho el doble clic", 1, 
         "No pasa nada", 0, 
         "c", 
         "", 
         ),                 
]

const NUM_PREGUNTAS = preguntas.length;