const preguntas = [
   new Pregunta(
      1, 
      "radio", 
      "¿Qué tipo de Software es Power BI?", 
      "-", 
      "Es un software de Inteligencia de Negocios", 1, 
      "Una herramienta para unificar datos.", 0, 
      "Es una aplicación que se utiliza en Big Data", 0, 
      "Es un complemento al Microsoft Excel", 0, 
      "a", 
      "", 
      ),
      
      new Pregunta(
      2, 
      "radio", 
      "¿Cuales herramientas conforman el Power BI Desktop?", 
      "-", 
      "Power Query, Power Pivot y Power View", 1, 
      "Power Data, Power Query y Power View", 0, 
      "Power Query, Power BI Gateways y Power View", 0, 
      "ETL, Power Pivot y DAX", 0, 
      "a", 
      "", 
      ),
      
      new Pregunta(
      3, 
      "radio", 
      "¿Cómo se llama la herramienta que utiliza Power BI para la adquisición y la transformación de los datos?", 
      "-", 
      "ETL", 0, 
      "Power Query", 1, 
      "Power Pivot", 0, 
      "Lenguaje M", 0, 
      "b", 
      "", 
      ),
      
      new Pregunta(
      4, 
      "radio", 
      "¿Es posible combinar con Power BI diferentes documentos si comparten la misma estructura?", 
      "-", 
      "No, estos se debem importar y relacionar", 0, 
      "Si es posible, mediante la herramienta Power Query", 1, 
      "Es posible, pero para hacerlo hay que escribir un procedimiento en Lenguaje M", 0, 
      "Se puede hacer mediante la utilización de visuales.", 0, 
      "b", 
      "", 
      ),
      
      new Pregunta(
      5, 
      "radio", 
      "¿Cual es la función del componente Power Pivot? (Selecciona la opción  más apropiada)", 
      "-", 
      "Power Pivot se encarga de la adquisición y la transformación de los datos.", 0, 
      "Power Pivot se encarga de mostrar los datos en forma de Tablas Dinámicas.", 0, 
      "Power Pivot se encarga de relacionar tablas, crear medidas y columnas calculadas.", 1, 
      "Power Pivot permite cambiar la forma en la que se relacionan las tablas importadas.", 0, 
      "c", 
      "", 
      ),
      
      new Pregunta(
      6, 
      "radio", 
      "¿Cómo se generan las nuevas columnas calculadas en Power Pivot?", 
      "-", 
      "Creando fórmulas como las de Excel, indicando las celdas donde se encuentran los datos y utilizando los mismos operadores.", 0, 
      "Creando fórmulas similares a las que utiliza Excel en las Tablas de Datos, es decir se indica el nombre de la tabla seguido del campo entre corchetes y utilizando los mismos operadores.", 0, 
      "Creando fórmulas similares a las que utiliza Excel en las Tablas de Datos, se utilizan los mismos operadores, pero las funciones DAX varían a pesar de ser muy similares.", 1, 
      "El Power Pivot no es el componente encargado de crear fórmulas sino el Power Query.", 0, 
      "c", 
      "", 
      ),
      
      new Pregunta(
      7, 
      "radio", 
      "¿Qué es una medida y qué icono se le asocia?", 
      "-", 
      "Una medida es un cálculo estadístico que se realiza en todo el set de datos. Se asocia al icono de sumatoria.", 0, 
      "Una medida es un cálculo agregado que se realiza en todo el set de datos. Se asocia al icono de calculadora.", 1, 
      "Una medida es un cálculo que se realiza en todo el set de datos. Se asocia al icono de tabla con un sumatorio sobre el  mismo.", 0, 
      "Una medida es un cálculo agregado que se realiza en todo el set de datos, que no muestra valores en Power Pivot y por tanto no tiene un icono asociado.", 0, 
      "b", 
      "", 
      ),
      
      new Pregunta(
      8, 
      "radio", 
      "¿Qué función tiene el componente Power View?", 
      "-", 
      "Es el componente que permite construir los informes (constituidos por Dashboards y Cuadros de Mando).", 1, 
      "Es el componente donde se visualiza el resultado de los cálculos realizados sobre los conjuntos de datos.", 0, 
      "Es la pantalla que permite visualizar la estructura de tablas y sus relaciones.", 0, 
      "Es el componente que permite realizar el proceso ETL de Extracción, Carga y Transformación de los Datos", 0, 
      "a", 
      "", 
      ),
      
      new Pregunta(
      9, 
      "radio", 
      "¿Cuáles son los bloques de creación básicos del Power View?", 
      "-", 
      "Campos, Relaciones y Medidas", 0, 
      "Iconos, Visuales, Conjunto de Datos, Paneles e Informes", 1, 
      "Queries, Data y Visuales", 0, 
      "Tablas, Transformaciones e Informes", 0, 
      "b", 
      "", 
      ),
      
      new Pregunta(
      10, 
      "radio", 
      "¿Qué es un Visual?", 
      "-", 
      "Es el conjunto de aplicaciones que conforman Power Bi y que permite analizar datos y compartir información.", 0, 
      "Es la interface que permite crear consultas en M, seleccionando una serie de opciones, sin saber programar.", 0, 
      "Son elementos utilizados en los informes de Power BI, para mostrar la información de diferente manera, usualmente de forma gráfica.", 1, 
      "Es todo lo que se muestra en los informes de Power BI", 0, 
      "c", 
      "", 
      ),
      new Pregunta(
         11, 
         "radio", 
         "¿Qué sucede si se selecciona un punto de datos en uno de los objetos visuales de un Panel?", 
         "-", 
         "Todos los demás objetos visuales de la página que contienen ese dato cambian para adaptarse a la selección.", 1, 
         "Se atenúan los colores de aquellos puntos de datos que no han sido seleccionados.", 0, 
         "Ocultará el resto de  las visualizaciones de la página", 0, 
         "Se genera una tabla de datos, con los datos de origen que dieron lugar al visual", 0, 
         "a", 
         "", 
         ),
         
         new Pregunta(
         12, 
         "radio", 
         "¿A qué nivel de la empresa se dirige el Power BI?", 
         "-", 
         "Al nivel Operacional", 0, 
         "A los trabajadores del conocimiento", 0, 
         "Al nivel Estratégico", 0, 
         "Tanto a nivel Gerencial como al Estratégico", 1, 
         "d", 
         "", 
         ),
         
         new Pregunta(
         13, 
         "radio", 
         "¿Con qué  fuentes de datos puede trabajar Power BI?", 
         "-", 
         "Datos Gráficos", 0, 
         "Datos Estructurados", 1, 
         "Datos No estructurados", 0, 
         "Datos Híbridos", 0, 
         "b", 
         "", 
         ),
         
         new Pregunta(
         14, 
         "checkbox", 
         "¿De qué elementos adolece el Power BI Desktop, versión gratuita? (selecciona las que procedan)", 
         "-", 
         "Establecimiento de niveles de privacidad", 0.33, 
         "Flexibilidad para publicar informes en toda la empresa", 0.33, 
         "Un servidor de informes de Power BI", 0.33, 
         "Capacidad para importar datos de Excel", 0, 
         "a,b,c", 
         "", 
         ),
         
         new Pregunta(
         15, 
         "radio", 
         "¿Desde dónde se crean las relaciones entre tablas en Power Pivot? (selecciona la más adecuada)", 
         "-", 
         "Las relaciones se detectan automáticamente durante la carga.", 0, 
         "Creando una tabla nueva para combinar los campos en ella", 0, 
         "Con el botón Relaciones, el cual nos lleva al modelo de datos.", 0, 
         "Las relaciones se detectan automáticamente, pero podemos cambiarlas desde el modelo de datos.", 1, 
         "d", 
         "", 
         ),
         
         new Pregunta(
         16, 
         "radio", 
         "¿Cómo se editan las relaciones entre tablas en Power BI?", 
         "-", 
         "Haciendo doble clic sobre la linea de relación", 1, 
         "En la pestaña Inicio, opción en Administrar relaciones", 0, 
         "Al realizar la transformación, desde Power Query", 0, 
         "No es posible editar las relaciones entre tablas", 0, 
         "a", 
         "", 
         ),
         
         new Pregunta(
         17, 
         "radio", 
         "¿Desde que componente de Power BI se pueden crear Tablas Dinámicas?", 
         "-", 
         "Desde Power Pivot", 0, 
         "Desde Power View", 1, 
         "Desde Power Query", 0, 
         "Desde DAX", 0, 
         "b", 
         "", 
         ),
         
         new Pregunta(
         18, 
         "radio", 
         "¿Cómo se categoriza un campo como de tipo geográfico para utilizarlo en mapas?", 
         "-", 
         "Desde la pestaña Modelado en la lista desplegable Categoría de datos.", 1, 
         "No es posible, no existen campos de tipo Geográfico", 0, 
         "El tipo de campo debe venir definido desde la Fuente de Datos.", 0, 
         "Al realizar las transfromaciones con Power Query.", 0, 
         "a", 
         "", 
         ),
         
         new Pregunta(
         19, 
         "radio", 
         "¿Es posible cambiar la información de las Fuentes de Datos desde Power BI?", 
         "-", 
         "Sí, utilizando un conector", 0, 
         "No, la información de las Fuentes de Datos va en un sentido unidireccional, Power Bi, solo lee datos de las fuentes.", 1, 
         "Depende del tipo de Fuente de Datos", 0, 
         "Si, de hecho los datos se actualizan automáticamente.", 0, 
         "b", 
         "", 
         ),
         
         new Pregunta(
         20, 
         "radio", 
         "¿Cómo se instalan nuevos visuales?", 
         "-", 
         "Todos los visuales con que cuenta Power BI ya se encuentran instalados y se muestran en la parte de la derecha.", 0, 
         "En realidad no se instalan si no que se pueden activar más.", 0, 
         "Se seleccionan los puntos suspensivos en la parte inferior del panel de Visualización y se Importan desde un archivo o desde la tienda.", 1, 
         "Actualizando la versión de Power BI, se accede a nuevos visuales.", 0, 
         "c", 
         "", 
         ),
          
]

const NUM_PREGUNTAS = preguntas.length;